require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LiquidTemplatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LiquidTemplate. As you add validations to LiquidTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { content: '{{ name }}' }
  }

  let(:invalid_attributes) {
    { content: '{{ name' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LiquidTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all liquid_templates as @liquid_templates" do
      liquid_template = LiquidTemplate.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:liquid_templates)).to eq([liquid_template])
    end
  end

  describe "GET #show" do
    it "assigns the requested liquid_template as @liquid_template" do
      liquid_template = LiquidTemplate.create! valid_attributes
      get :show, params: {id: liquid_template.to_param}, session: valid_session
      expect(assigns(:liquid_template)).to eq(liquid_template)
    end
  end

  describe "GET #new" do
    it "assigns a new liquid_template as @liquid_template" do
      get :new, params: {}, session: valid_session
      expect(assigns(:liquid_template)).to be_a_new(LiquidTemplate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested liquid_template as @liquid_template" do
      liquid_template = LiquidTemplate.create! valid_attributes
      get :edit, params: {id: liquid_template.to_param}, session: valid_session
      expect(assigns(:liquid_template)).to eq(liquid_template)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LiquidTemplate" do
        expect {
          post :create, params: {liquid_template: valid_attributes}, session: valid_session
        }.to change(LiquidTemplate, :count).by(1)
      end

      it "assigns a newly created liquid_template as @liquid_template" do
        post :create, params: {liquid_template: valid_attributes}, session: valid_session
        expect(assigns(:liquid_template)).to be_a(LiquidTemplate)
        expect(assigns(:liquid_template)).to be_persisted
      end

      it "redirects to the created liquid_template" do
        post :create, params: {liquid_template: valid_attributes}, session: valid_session
        expect(response).to redirect_to(LiquidTemplate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved liquid_template as @liquid_template" do
        post :create, params: {liquid_template: invalid_attributes}, session: valid_session
        expect(assigns(:liquid_template)).to be_a_new(LiquidTemplate)
      end

      it "re-renders the 'new' template" do
        post :create, params: {liquid_template: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { content: '{{ address }}' }
      }

      it "updates the requested liquid_template" do
        liquid_template = LiquidTemplate.create! valid_attributes
        put :update, params: {id: liquid_template.to_param, liquid_template: new_attributes}, session: valid_session
        liquid_template.reload
        expect(liquid_template.content).to eq(new_attributes[:content])
      end

      it "assigns the requested liquid_template as @liquid_template" do
        liquid_template = LiquidTemplate.create! valid_attributes
        put :update, params: {id: liquid_template.to_param, liquid_template: valid_attributes}, session: valid_session
        expect(assigns(:liquid_template)).to eq(liquid_template)
      end

      it "redirects to the liquid_template" do
        liquid_template = LiquidTemplate.create! valid_attributes
        put :update, params: {id: liquid_template.to_param, liquid_template: valid_attributes}, session: valid_session
        expect(response).to redirect_to(liquid_template)
      end
    end

    context "with invalid params" do
      it "assigns the liquid_template as @liquid_template" do
        liquid_template = LiquidTemplate.create! valid_attributes
        put :update, params: {id: liquid_template.to_param, liquid_template: invalid_attributes}, session: valid_session
        expect(assigns(:liquid_template)).to eq(liquid_template)
      end

      it "re-renders the 'edit' template" do
        liquid_template = LiquidTemplate.create! valid_attributes
        put :update, params: {id: liquid_template.to_param, liquid_template: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested liquid_template" do
      liquid_template = LiquidTemplate.create! valid_attributes
      expect {
        delete :destroy, params: {id: liquid_template.to_param}, session: valid_session
      }.to change(LiquidTemplate, :count).by(-1)
    end

    it "redirects to the liquid_templates list" do
      liquid_template = LiquidTemplate.create! valid_attributes
      delete :destroy, params: {id: liquid_template.to_param}, session: valid_session
      expect(response).to redirect_to(liquid_templates_url)
    end
  end

end
